SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `BDEasyBusiness` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BDEasyBusiness` ;

-- -----------------------------------------------------
-- Table `BDEasyBusiness`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDEasyBusiness`.`Usuarios` (
  `Mail` VARCHAR(45) NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `ApellidoUsuario` VARCHAR(45) NOT NULL,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `BaseDeDatos` VARCHAR(45) NULL,
  PRIMARY KEY (`Mail`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


